// src/leaves/schemas/leaves.enums.ts
export enum LeaveCategory {
  ANNUAL = 'ANNUAL',
  OTHER = 'OTHER',
  UNPAID = 'UNPAID',
  SICK = 'SICK',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  MISSION = 'MISSION',
  MARRIAGE = 'MARRIAGE',
}

export enum RoundingMethod {
  NONE = 'NONE',
  ARITHMETIC = 'ARITHMETIC',
  ALWAYS_UP = 'ALWAYS_UP',
  ALWAYS_DOWN = 'ALWAYS_DOWN',
}

export enum AccrualFrequency {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
}

export enum LeaveRequestStatus {
  DRAFT = 'DRAFT',
  PENDING_MANAGER = 'PENDING_MANAGER',
  PENDING_HR = 'PENDING_HR',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  ESCALATED = 'ESCALATED',
}

export enum ResetCriterion {
  HIRE_DATE = 'HIRE_DATE',
  FIRST_VACATION_DATE = 'FIRST_VACATION_DATE',
  REVISED_HIRE_DATE = 'REVISED_HIRE_DATE',
  WORK_RECEIVING_DATE = 'WORK_RECEIVING_DATE',
}

export enum AdjustmentSource {
  MANUAL = 'MANUAL',
  ACCRUAL = 'ACCRUAL',
  CARRY_FORWARD = 'CARRY_FORWARD',
  REQUEST_APPROVAL = 'REQUEST_APPROVAL',
  REQUEST_CANCELLATION = 'REQUEST_CANCELLATION',
  ENCASHMENT = 'ENCASHMENT',
}
